FROM theorem.personalrobotics.ri.cmu.edu:5555/personalrobotics/nginx:latest
MAINTAINER Clint Liddick <cliddick@andrew.cmu.edu>

RUN rm /etc/nginx/sites-enabled/default
COPY nginx.conf /etc/nginx/sites-available/snap
RUN ln -s /etc/nginx/sites-available/snap /etc/nginx/sites-enabled/snap

EXPOSE 80

CMD ["/usr/sbin/nginx"]
